development:
  adapter: postgresql
  encoding: unicode
  database: bookapp_development
  username: postgres
  password: postgres
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: bookapp_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: bookapp_test
  username: postgres
  password: postgres
